import {chromium} from 'playwright';import fs from 'node:fs/promises';
const base=process.env.REVIEW_URL||'http://127.0.0.1:4173';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1600,height:1100}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);await page.waitForSelector('#step-title:text("20帧整段读取")');
if(!(await page.locator('#stage-body').innerText()).includes('Flash接口未返回思考正文'))throw new Error('Missing honest Flash thought state');
await page.click('#frames-view');await page.locator('#timeline-list .step-item').nth(7).click();await page.waitForSelector('#step-title:text("第 8 帧")');
if(!(await page.locator('#stage-body').innerText()).includes('"move_m": 0'))throw new Error('Frame8 receipt absent');
await page.locator('#note-text').waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('#note-text').disabled);
const note='浏览器验收：第8帧仅原地旋转。'+Date.now();await page.fill('#note-text',note);await page.selectOption('#note-verdict','question');await page.click('#save-note');await page.waitForFunction(()=>document.querySelector('#save-indicator').textContent.includes('已保存到云端'));
await page.reload();await page.waitForFunction(n=>document.querySelector('#note-text').value===n,note);
const saved=await page.evaluate(async()=>await(await fetch('/api/notes/frame:common-91100-flash-full:8')).json());if(saved.note!==note)throw new Error('Annotation not persisted on server');
await page.getByRole('button',{name:'Gemma 4 · 31B',exact:true}).click();await page.click('#calls-view');await page.locator('#timeline-list .step-item').filter({hasText:'200帧读取'}).click();await page.waitForFunction(()=>document.querySelector('#stage-body').innerText.includes('Check Frame 8'));
await page.getByRole('button',{name:'完整输入',exact:true}).click();await page.waitForSelector('.request-message');await page.waitForFunction(()=>!document.querySelector('#stage-body').innerText.includes('载入完整上下文'));
if((await page.locator('.request-message').count())<2)throw new Error('Full request not reconstructed');
await page.getByRole('button',{name:'Qwen 3.8 · 27B',exact:true}).click();await page.locator('#timeline-list .step-item').filter({hasText:'200帧读取'}).click();await page.waitForFunction(()=>document.querySelector('#stage-body').innerText.includes('WRONG_COORDINATE_SCHEMA'));
await page.getByRole('button',{name:'返回的思考',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#stage-body').innerText.includes('These are guesses but plausible'));
await page.locator('.case-button').filter({hasText:'自主探索 91100'}).click();await page.waitForFunction(()=>document.querySelector('#run-description').innerText.includes('Claude Code'));
await page.getByRole('button',{name:'完整输入',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#stage-body').innerText.includes('请求设置与工具定义'));
await page.locator('.case-button').filter({hasText:'场景 91100'}).click();await page.getByRole('button',{name:'Gemini 3.8 Flash',exact:true}).click();await page.getByRole('button',{name:'返回的思考',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#stage-body').innerText.includes('Flash接口未返回思考正文'));
await fs.mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+2))throw new Error('Mobile horizontal overflow');
const download=page.waitForEvent('download');await page.click('#export-notes');const file=await download;await file.saveAs('test-results/notes-export.json');
if(errors.length)throw new Error(errors.join('\n'));
await fs.writeFile('test-results/browser-checks.json',JSON.stringify({passed:true,flash_missing_thought_explicit:true,frame_receipts:true,server_annotation_survives_reload:true,complete_context_reconstruction:true,qwen_schema_failure_explicit:true,actual_thought_text:true,autonomous_calls:true,mobile_no_overflow:true,notes_export:true},null,2));
console.log('Browser checks passed.');await browser.close();
